services:
  mongodb:
    image: mongo:4.4
    container_name: my-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=jwt-basic
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017/jwt-basic?authSource=admin
      - JWT_SECRET=secret
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    container_name: react_app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
