services:
# Servicio MongoDB
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    #Servicio para mongo express
    image: mongo-express:1.0
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSER: root
      ME_CONFIG_MONGODB_ADMINPASS: example
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: hlanz
    depends_on:
      - mongo

  # Servicio backend de node 
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app/     # Monta el directorio actual en /app dentro del contenedor
      - /app/node_modules 
    depends_on:
      - mongo
    
  # Servicio frontend de react
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    depends_on:
      - backend

# Volumen para la persistencia de las bases de datos
volumes:
  mongo_data: